### ISSUE TITLE
Iterators.partition gives suboptimal partitions for multithreading

### ISSUE THREAD

**Issue by nalimilan** [jondeuce/DECAES.jl#37]
I've noticed that you use a `tforeach` implementation inspired by ThreadTools. I did the same for DataFrames.jl, and we noticed that `Iterators.partition` doesn't give very good results since the last chunk will generally be smaller than others, which is bad for load balancing. See https://github.com/JuliaData/DataFrames.jl/pull/2661#discussion_r593959480 for details and a possible solution. I hope this is useful.

**Comment by jondeuce** [comment]
Thanks for the tip! I actually have gone through several iterations of `tforeach`-type abstractions, so I'm sure your findings will be helpful. I've found it particularly tricky to print progress updates to a log file and/or to the console during high throughput multithreaded workloads without compromising performance. I don't think DataFrames.jl does progress printing, but if you do I'd be very interested in any tips there, too!

**Comment by nalimilan** [comment]
Unfortunately I don't really have tips in that area. I guess I would have checked a counter to print progress only every N iterations, but of course that depends on the particular case.

**Comment by jondeuce** [comment]
Yup, that's essentially what I've settled on. ProgressMeter.jl worked _almost_ out of the box, but the "live updating" progress bar (essentially, repeatedly printing over itself) would occasionally not show up. My current solution works quite well, if a bit hacky: https://github.com/jondeuce/DECAES.jl/blob/017ade4edc58cfcc5e0e08f91838cf33b2eb63bb/src/utils.jl#L131
But I digress ;)
