### ISSUE TITLE
When first echo time is not equal to --TE argument

### ISSUE THREAD

**Issue by orie2409** [jondeuce/DECAES.jl#54]
Hi again,

The argument --TE assumes the echo times are TE, 2TE, 3TE, ... and so on; is that correct? 

My echo times are 15ms, 20ms, 25ms, 30ms. I set TE=5e-3, however if I understand correctly, this assumes the first TE=5ms. Is it possible for you to add an optional argument start_TE, or is there another solution you can recommend please?

Thanks very much.

**Comment by jcd1994** [comment]
Unfortunately, this is not currently possible. I have thought about allowing different echo time schemes in the past, but there was never any demand.

Note also that if you are interested in white matter imaging in the brain, you are losing the vast majority of the fast-decaying signal by starting at a later echo time. If you are interested in longer T2 components, however, it would probably be okay.

**Comment by jondeuce** [comment]
Unfortunately, this is not currently possible. I have thought about allowing different echo time schemes in the past, but there was never any demand.

Note also that if you are interested in white matter imaging in the brain, you are losing the vast majority of the fast-decaying signal by starting at a later echo time. If you are interested in longer T2 components, however, it would probably be okay.

**Comment by orie2409** [comment]
Thanks for your response, I'll close this issue now.
