### ISSUE TITLE
T2* fitting

### ISSUE THREAD

**Issue by Laura2305** [jondeuce/DECAES.jl#64]
Is it possible to remove the EPG computation and use this package's functions for T2* fitting?

**Comment by jondeuce** [comment]
Sort of - it depends what you're interested in. This package does multi-exponential fitting with fixed logarithmically spaced decay times (which normally we interpret as T2 values, but see below), so if you are interested in **mono-exponential** T2* fits then no this package doesn't do that.

However, if you want **multi-exponential** T2* spectra, the output of the EPG algorithm is equivalent to pure exponential decay if you set the flip angle to 180 degrees (via the `--SetFlipAngle 180` flag) and T1 to an arbitrarily large constant (via the `--T1 Inf` flag). Then, you can interpret the output from the multi-exponential fit as a T2* spectrum.

**Comment by Laura2305** [comment]
Thanks! This is very helpful.
